<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="index.php?c=user" method="POST">
        <input type="text" name="usernameRegister" placeholder="nombre de usuario">
        <input type="password" name="passwordRegister">
        <input type="password" name="passwordRegister2" placeholder="repite la contraseña">
        <input type="submit" value="registrar">
    </form>
    
</body>
</html>